version: '3.9'

networks:
  choix_option_net:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'php'
    ports:
      - '${APP_PORT}:80'
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@${DB_SERVER}:${DB_PORT}/${MYSQL_DB}'
      - 'USER_DATABASE_URL=mysql://${MYSQL_USER_USER}:${MYSQL_PASS_USER}@${DB_SERVER_USER}:${DB_PORT}/${MYSQL_DB_USER}'
      - 'MAILER_DSN=smtp://mailhog:1025'
    volumes:
      - ./project:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - choix_option_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'phpmyadmin'
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - '${APP_DB_ADMIN_PORT}:80'

  adminer:
    image: adminer
    container_name: 'adminer'
    ports:
      - '8104:8080'
    volumes:
      - ./docker/adminer/adminer.css:/var/www/html/adminer.css

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MH_STORAGE=memory
    volumes:
      - ./docker/mailhog:/data
    networks:
      - choix_option_net
